on: push
name: Build Angular
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - run: npm install
      - run: npm run build
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: frontend
          tags: ${{ github.sha }}
